### ISSUE TITLE
Migrate to ShareDB

### ISSUE THREAD

**Issue by cklokmose** [cklokmose/Webstrates#6]
Webstrates is currently running ShareJS 0.7.3. ShareJS 0.7 is no longer maintained but has been forked to ShareDB (https://github.com/share/sharedb)

ShareJS 0.7.3 has a bug in handling out of order operations under heavy server load.

**Comment by cklokmose** [comment]
Here's an example of how to setup the webclient for ShareDB
https://github.com/lubaochuan/sharedb_examples

**Comment by Marc-Emmanuel** [comment]
Actually, this is working for browsing and editing. But when you want to access ops, this will make the server down because of ```undefined``` op array passed by ```backend.getOps```. I was not able to figure why...
